<a href="https://colab.research.google.com/github/lee7py/2021-py-DNN/blob/main/code/1-0%20myfirst_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [ ]:
import sklearn as sk
sk.__version__

'0.24.2'

In [ ]:
import site
site.getsitepackages()

['C:\\Anaconda3\\envs\\aidnn',
 'C:\\Anaconda3\\envs\\aidnn\\lib\\site-packages']

In [ ]:
a, b = 10, 20

In [ ]:
a + b

30

In [ ]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
x.numpy()

10

In [ ]:
y = tf.constant(20)
y

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [ ]:
y.numpy()

20

In [ ]:
x + y

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
z = x + y
z

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
z.numpy()

30

In [ ]:
z.shape

TensorShape([])

In [ ]:
m = tf.constant([1, 2, 3])
m

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [ ]:
m.numpy()

array([1, 2, 3])

In [ ]:
tf.executing_eagerly()

True