<a href="https://colab.research.google.com/github/lee7py/2021-py-DNN/blob/main/code/1-1%20mydnn_basic_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Manipulation

In [ ]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
print(tf.__version__)

2.5.0


## Simple Array

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
2
(4, 3)


## Shape, Rank, Axis

In [ ]:
t = tf.constant([1,2,3,4])
tf.shape(t).numpy()

array([4], dtype=int32)

In [ ]:
t.shape

TensorShape([4])

In [ ]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).numpy()

array([2, 2], dtype=int32)

In [ ]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(t)

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)


In [ ]:
tf.shape(t).numpy()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
a = [
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]
a

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [ ]:
pp.pprint(a)

[   [   [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]


In [ ]:
print(a)
a

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]


[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS multiply

In [ ]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).numpy()

array([[12.]], dtype=float32)

In [ ]:
(matrix1*matrix2).numpy()

array([[6., 6.],
       [6., 6.]], dtype=float32)

## Watch out broadcasting

In [ ]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).numpy()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).numpy()

array([[5., 5.]], dtype=float32)

## Random values for variable initializations 

In [ ]:
tf.random.normal([3]).numpy()

array([ 1.2534605 , -0.9343768 ,  0.82752836], dtype=float32)

In [ ]:
tf.random.uniform([3]).numpy()

array([0.10154951, 0.00404978, 0.44939637], dtype=float32)

In [ ]:
tf.random.uniform([2, 3]).numpy()

array([[0.27430987, 0.15010607, 0.9183091 ],
       [0.6283765 , 0.21066785, 0.5335195 ]], dtype=float32)

## Reduce Mean/Sum

In [ ]:
tf.reduce_mean([1, 2], axis=0).numpy()

1

In [ ]:
tf.reduce_mean([1., 2.], axis=0).numpy()

1.5

In [ ]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).numpy()

2.5

In [ ]:
tf.reduce_mean(x, axis=0).numpy()

array([2., 3.], dtype=float32)

In [ ]:
tf.reduce_mean(x, axis=1).numpy()

array([1.5, 3.5], dtype=float32)

In [ ]:
tf.reduce_mean(x, axis=-1).numpy()

array([1.5, 3.5], dtype=float32)

In [ ]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_sum(x).numpy()

10.0

In [ ]:
tf.reduce_sum(x, axis=0).numpy()

array([4., 6.], dtype=float32)

In [ ]:
tf.reduce_sum(x, axis=1).numpy()

array([3., 7.], dtype=float32)

In [ ]:
tf.reduce_sum(x, axis=-1).numpy()

array([3., 7.], dtype=float32)

In [ ]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).numpy()

5.0

## Argmax with axis

In [ ]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).numpy()

array([1, 0, 0], dtype=int64)

In [ ]:
tf.argmax(x, axis=1).numpy()

array([2, 0], dtype=int64)

In [ ]:
tf.argmax(x, axis=-1).numpy()

array([2, 0], dtype=int64)

## Reshape, squeeze, expand_dims

In [ ]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [ ]:
tf.reshape(t, shape=[-1, 3]).numpy()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
tf.reshape(t, shape=[-1, 1, 3]).numpy()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [ ]:
a = np.array([[0], [1], [2]])
print(a.shape)
b = tf.squeeze(a)
print(b.shape)
b.numpy()

(3, 1)
(3,)


array([0, 1, 2])

In [ ]:
a = np.array([[[0, 1], [2, 3]]])
print(a.shape)
b = tf.squeeze(a)
print(b.shape)
b.numpy()

(1, 2, 2)
(2, 2)


array([[0, 1],
       [2, 3]])

In [ ]:
a = np.array([[[0, 1]], [[2, 3]]])
print(a.shape)
b = tf.squeeze(a)
print(b.shape)
b.numpy()

(2, 1, 2)
(2, 2)


array([[0, 1],
       [2, 3]])

In [ ]:
a = np.array([0, 1, 2])
print(a.shape)
b = tf.expand_dims(a, 0)
print(b.shape)
b.numpy()

(3,)
(1, 3)


array([[0, 1, 2]])

In [ ]:
a = np.array([0, 1, 2])
print(a.shape)
b = tf.expand_dims(a, 1)
print(b.shape)
b.numpy()

(3,)
(3, 1)


array([[0],
       [1],
       [2]])

## One hot

In [ ]:
# 차수가 하나 늘어나며, depth는 유형 종류의 수
tf.one_hot([[0], [1], [2], [0]], depth=3).numpy()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [ ]:
tf.one_hot([[0], [1], [2], [0]], depth=4).numpy()

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[1., 0., 0., 0.]]], dtype=float32)

In [ ]:
tf.one_hot([[0], [1], [2], [0]], depth=5).numpy()

array([[[1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0.]],

       [[0., 0., 1., 0., 0.]],

       [[1., 0., 0., 0., 0.]]], dtype=float32)

In [ ]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
print(t.numpy())
tf.reshape(t, shape=[-1, 3]).numpy()

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

문제

In [ ]:
# 차수가 하나 늘어나며, depth는 유형 종류의 수
tf.one_hot([[0], [1], [2], [0]], depth=3).numpy()[2]

array([[0., 0., 1.]], dtype=float32)

## casting

In [ ]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).numpy()

array([1, 2, 3, 4])

In [ ]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).numpy()

array([1, 0, 1, 0])

## Stack

In [ ]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).numpy()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [ ]:
tf.stack([x, y, z], axis=1).numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## Ones like and Zeros like

In [ ]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).numpy()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
tf.zeros_like(x).numpy()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

## Zip


In [ ]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [ ]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [ ]:
t1 = tf.transpose(t, [0, 1, 2])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>


In [ ]:
t1 = tf.transpose(t, [0, 2, 1])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 3, 2])
<tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])>


In [ ]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])>


In [ ]:
t1 = tf.transpose(t, [1, 2, 0])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 3, 2])
<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])>


In [ ]:
t1 = tf.transpose(t, [2, 0, 1])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([3, 2, 2])
<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 0,  3],
        [ 6,  9]],

       [[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]]])>


In [ ]:
t1 = tf.transpose(t, [2, 1, 0])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([3, 2, 2])
<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])>
