<a href="https://colab.research.google.com/github/lee7py/2021-py-DNN/blob/main/code/2-2%20mydnn_tf_v1code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [ ]:
 %tensorflow_version 1.x

TensorFlow is already loaded. Please restart the runtime to change versions.


In [ ]:
# 텐서플로 1.0 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 1.x
except Exception:
    pass

import tensorflow as tf
tf.__version__

TensorFlow 1.x selected.


'1.15.2'

In [ ]:
a = 10
b = 10
print(a + b)

20


In [ ]:
a = 10
b = 10
print(tf.add(a, b))

Tensor("Add:0", shape=(), dtype=int32)


In [ ]:
a = 10
b = 10
print(tf.add(a, b))

sess = tf.Session()
print(sess.run(tf.add(a, b)))
sess.close()

Tensor("Add_1:0", shape=(), dtype=int32)
20


In [ ]:
import tensorflow as tf

hello = tf.constant('Hello World!')

sess = tf.Session()
print(sess.run(hello))
sess.close()

b'Hello World!'


In [ ]:
a = tf.constant(5)
b = tf.constant(3)
sess = tf.Session()

print(sess.run(a+b))
sess.close()

8


In [ ]:
c = tf.constant('Hello, world!')

with tf.Session() as sess:
    print(sess.run(c))

b'Hello, world!'


In [ ]:
x = tf.constant(1.)
bool = tf.constant(False)
res = tf.cond(bool, lambda: tf.add(x, 1.), lambda: tf.add(x, 10.))

with tf.Session() as sess:
    print( sess.run(res))

11.0


In [ ]:
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)

d = a * b + c

with tf.Session() as sess:
    print(sess.run(d))

[52.]


In [ ]:
a = tf.constant(5, dtype=tf.float32)
#a = 5
with tf.Session() as sess:
    print(sess.run(a))

5.0


In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([5, 6, 7])

with tf.Session() as sess:
    print(sess.run(x+y))


[ 6  8 10]


In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([[1], [2], [3]])

with tf.Session() as sess:
    print(sess.run(x+y))

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
a = 2
b = 3
c = tf.add(a, b, name='Add')
print(c)

Tensor("Add_7:0", shape=(), dtype=int32)


In [ ]:
a = 2
b = 3
c = tf.add(a, b, name='Add')

sess = tf.Session()
print(sess.run(c))
sess.close()
 

5


In [ ]:
a = 2
b = 3
c = tf.add(a, b, name='Add')

with tf.Session() as sess:
    print(sess.run(c))

5


In [ ]:
import tensorflow as tf
x = 2
y = 3
add_op = tf.add(x, y, name='Add')
mul_op = tf.multiply(x, y, name='Multiply')
pow_op = tf.pow(add_op, mul_op, name='Power')
useless_op = tf.multiply(x, add_op, name='Useless')

with tf.Session() as sess:
    pow_out, useless_out = sess.run([pow_op, useless_op])
    print(pow_out, useless_out)

15625 10


In [ ]:
a = tf.constant(2.)
b = tf.constant(3.)
c = tf.constant(5.)

# Some more operations.
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

with tf.Session() as sess:
    print("mean =", sess.run(mean))
    print("sum =", sess.run(sum))

mean = 3.3333333
sum = 10.0


In [ ]:
# Matrix multiplications.
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

gop = tf.matmul(matrix1, matrix2)

with tf.Session() as sess:
    print(sess.run(gop))

[[19. 22.]
 [43. 50.]]


In [ ]:
tf.executing_eagerly()

False

In [ ]:
a = 2
b = 3
c = tf.add(a, b, name='Add')
print(c.eval())

ValueError: ignored

In [ ]:
interactive_sess = tf.InteractiveSession()
a = 2
b = 3
c = tf.add(a, b, name='Add')
print(c.eval())

5


In [ ]:
x = tf.constant(1.)
bool = tf.constant(False)
res = tf.cond(bool, lambda: tf.add(x, 1.), lambda: tf.add(x, 10.))

print(res.eval())

11.0


In [ ]:
# 텐서플로 1.0 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
tf.__version__

'2.5.0'

In [ ]:
tf.executing_eagerly()

True

In [ ]:
import tensorflow as tf

hello = tf.constant('Hello World!')
print(hello)
print(hello.numpy())

tf.Tensor(b'Hello World!', shape=(), dtype=string)
b'Hello World!'


In [ ]:
a = tf.constant(5)
b = tf.constant(3)
a+b
(a+b).numpy()

8

In [ ]:
import tensorflow as tf

a = tf.constant(5)
b = tf.constant(3)
sess = tf.Session()

print(sess.run(a+b))
sess.close()

8


In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.
