In [1]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [2]:
import sklearn as sk
sk.__version__

'0.24.2'

In [3]:
import site
site.getsitepackages()

['C:\\Anaconda3\\envs\\aidnn',
 'C:\\Anaconda3\\envs\\aidnn\\lib\\site-packages']

In [4]:
a, b = 10, 20

In [5]:
a + b

30

In [6]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [8]:
x.numpy()

10

In [9]:
y = tf.constant(20)
y

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [10]:
y.numpy()

20

In [11]:
x + y

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [12]:
z = x + y
z

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [13]:
z.numpy()

30

In [14]:
z.shape

TensorShape([])

In [15]:
m = tf.constant([1, 2, 3])
m

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [16]:
m.numpy()

array([1, 2, 3])

In [17]:
tf.executing_eagerly()

True